MNO_DEVPL_HOST: http://localhost:5001
MNO_DEVPL_API_PATH: /api/config/v1/marketplaces
MNO_DEVPL_ENV_NAME: demo-app-rails
MNO_DEVPL_ENV_KEY: 3fbe8317-24d2-488b-8208-27a03cd52e05
MNO_DEVPL_ENV_SECRET: MtAFQm9zkI9WDy07uVCsmw
